name: Run PSScriptAnalyzer Tests
on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  psscriptanalyzer:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write
        checks: write
        pull-requests: write
        security-events: write 
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4  

      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
            .\runSecurity.ps1

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          token: ${{ secrets.GITHUB_TOKEN }}